# Welcome to Jekyll!

# Website settings
title: "Jordan Farrer"
description: "Jordan's github blog"
keywords: "Jordan,Farrer,Wharton,Uber,Maple,Deloitte,Fulbright"
baseurl: "/"
url: "http://jrfarrer.github.io"
#url: "http://127.0.0.1:4000"

# author
author:
  name: 'Farrer'
  first_name: 'Farrer'
  last_name: 'Jordan'
  email: 'jordanrfarrer@gmail.com'
  facebook_username: 'JordanFarrer'
  github_username: 'jrfarrer'
  avatar: 'static/img/landing/Jordan.jpg'
  linkedin: 'jordanfarrer'
  desc: 'MBA student at Wharton with a strong affinity for R. Previously a data analyst at Uber and teacher in Indonesia.'


# blog img path
img_path: 'https://github.com/jrfarrer/jrfarrer.github.io/blob/master/static/img/blog/'
#img_path: '/Users/Jordan/Dropbox/Blog/jalpc_jekyll_theme/static/img/blog/'

# google analytics
ga:
  id: UA-89515063-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
